version: "3.8"

services:
  lab-grader:
    container_name: lab-grader
    build: ./lab-grader
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./lab-grader:/app
    ports:
      - 8000:8000
    working_dir: /app
    restart: on-failure
    env_file:
      - lab-grader/.env
    networks:
      service-network:

#  telegram-client-bot:
#    container_name: telegram-client-bot
#    build: ./telegram-client-bot
#    command: python main.py
#    volumes:
#      - ./telegram-client-bot:/app
#    working_dir: /app
#    restart: on-failure
#    env_file:
#      - telegram-client-bot/.env
#    networks:
#      service-network:

  telegram-admin-bot:
    container_name: telegram-admin-bot
    build: ./telegram-admin-bot
    command: python main.py
    volumes:
      - ./telegram-admin-bot:/app
    working_dir: /app
    restart: on-failure
    env_file:
      - telegram-admin-bot/.env
    networks:
     service-network:

#  discord-client-bot:
#    container_name: discord-client-bot
#    build: ./discord-client-bot
#    command: python main.py
#    volumes:
#      - ./discord-client-bot:/app
#    working_dir: /app
#    restart: on-failure
#    env_file:
#      - discord-client-bot/.env
#    networks:
#      service-network:

networks:
  service-network:
    driver: bridge
